#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := open-voting-client

EXTRA_COMPONENT_DIRS := $(abspath drv)	$(abspath lvgl)

include $(IDF_PATH)/make/project.mk

